name: Publish

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docs
        run: docker run --rm -v $(pwd):/workspace -w /workspace customcommander/webdev make build/docs

      - name: Publish Site
        run: docker run --rm -v $(pwd)/build:/workspace -w /workspace squidfunk/mkdocs-material:8.1.2 mkdocs gh-deploy --force

      - name: Cleanup
        run: docker-compose down
